name: White Paper
markdown: redcarpet
pygments: true
url: http://vinitkumar.me/white-paper
paginate: 8
description:     Jekyll theme for Programmers
intro: White Paper is a Jekyll theme most suited to be used on tech blogs that like their content to shine.
logo:             logo.png
disqus_shortname:
# url: http://gotchacode.com
#Comment out url when working locally to resolve base urls correctly
#url:

# Owner/author information
owner:
  name:           <your-name-here>
  avatar:         <avatar-image-link>
  email:          <your-email-address>
  # Social networking links used in footer. Update and remove as you like.
  twitter:
  github:
  stackexchange:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true